name: trids
channels:
  - nvidia/label/cuda-12.6.0
  - conda-forge

# Note: The version of PyTorch must be compatible with CUDA
# Here all of code are compiled with CUDA-12.6
dependencies:
  - python=3.12
  - openbabel>=3.1.1
  - pybind11>=2.13
  - spdlog>=1.16.0
  - cli11>=2.1.2
  - numpy>=2.0
  # If you want to compile this project on Windows, followig packages should be installed, 
  # and the version of PyTorch must be compatible with CUDA
  # - cmake=3.28
  # - cuda=12.6
  # - ninja
  # - vs2022-win_64
  # - zlib
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - torch==2.7.1
    - nvidia-nvtx-cu12
    - nvidia-cudnn-cu12
